DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER(
  CUSTOMER_ID INT PRIMARY KEY,
  CUSTOMER_NAME VARCHAR(255),
  COMPANY VARCHAR(255)
);

INSERT INTO CUSTOMER(
  CUSTOMER_NAME
  , COMPANY
) VALUES (
  'libedi'
  , 'Freelancer'
);